name: CycleMap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: CycleMap - Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
